name: Github Pipelines

on:
  push:
    branches:
      - feat/GG-9-gtihub-pipelines

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: npm run lint  

      - name: Test
        run: npm test

      - name: Build
        run: npm run build  
         
